### PR TITLE
thruActivated as a property of the Transport layer

### PR DESCRIPTION
**Pull request by lathoub**

### CODE REVIEW

**Comment by lathoub** [comment]
This PR has no effect on the current release of the library. 2 options:

- update the current Release (not bumping the version nr)
- issue a new Release and bump the Release from 5.0.0 to 5.0.1

I suggest to go for option 1, as nothing changes in the Release (the changes are in the other Transport Layers)

**Comment by franky47** [comment]
I'd rather have a version change to facilitate logging in the changelog, releases should be immutable.

**Comment by franky47** [comment]
Also because there is an API change, the dependencies will have to be synchronized, I don't know if you can require a version range in your transport libraries, but we'll have to release the core first, then the updated transports.

**Comment by lathoub** [comment]
I'll change the versions in the Transport layer and issue a Release - can you make a Release of 5.0.1 as well pls?

**Comment by franky47** [comment]
Yes, it's almost ready, I'm updating the documentation.

**Pull request merged**
